### ISSUE TITLE
ImportFBX Errors

### ISSUE THREAD

**Issue by attmaxess** [hrmrzizon/CustomSkinningExample#13]
![image](https://user-images.githubusercontent.com/13692204/50583090-de11bb80-0e99-11e9-885a-ec866851a5e2.png)
Hi hrmrzizon,
All of the FBX are failed to import like image. Do you know what might be wrong?!

**Comment by lybmccree** [comment]
https://github.com/keijiro/CMUMocap
I find it in Acknowledgement.txt
just replace all animation
